---
- name: Playbook Cisco ACI - Cleanup
  hosts: aci_host
  gather_facts: false
  # This makes Ansible look for the collection without depending on cfg file
  collections:
    - cisco.aci

  tasks:
    - name: Delete tenant on ACI
      cisco.aci.aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}" 
        password: "{{ password }}"
        tenant: "Tenant_Ansible_AWX"
        state: absent
        validate_certs: false
