---
- name: Playbook Cisco ACI
  hosts: localhost
  gather_facts: false
  
  # This makes Ansible look for the collection without depending on cfg file
  collections:
    - cisco.aci

  tasks:
    - name: Crear un nuevo Tenant en ACI
      cisco.aci.aci_tenant:
        host: "{{ aci_host }}"
        username: "{{ aci_user }}"
        password: "{{ aci_password }}"
        tenant: "Tenant_Nueva_Org"
        description: "Created via Ansible AWX - Project [Cloud Repo]"
        state: present
        validate_certs: false
