---
- name: Automatización de Cisco ACI
  hosts: localhost
  gather_facts: false
  
  # Define aquí tus credenciales o usa "Credentials" en AWX
  vars:
    aci_info:
      host: "172.16.100.65" # Cambia por la IP de tu APIC
      username: "admin"
      password: "Cisco!123"
      validate_certs: false

  tasks:
    - name: Crear un nuevo Tenant en ACI
      cisco.aci.aci_tenant:
        host: "{{ aci_info.host }}"
        username: "{{ aci_info.username }}"
        password: "{{ aci_info.password }}"
        validate_certs: "{{ aci_info.validate_certs }}"
        tenant: "AWX_PROD_TENANT"
        description: "Tenant creado desde Ansible AWX"
        state: present
      register: aci_result

    - name: Mostrar resultado de la operación
      ansible.builtin.debug:
        var: aci_result
